notifications:
  email: false
language: ruby
sudo: false
rvm:
  - 2.2.3

matrix:
  include:
    - rvm: 2.2.2
      env: "RAILS_VERSION=4.1.13"
    - rvm: 2.1.6
      env: "RAILS_VERSION=4.2.4"
  allow_failures:
    - rvm: jruby
      env: "RAILS_VERSION=4.2.4 JRUBY_OPTS=\"-J-Xms512m -J-Xmx1024m\""
    - rvm: 1.9.3

env:
 - "RAILS_VERSION=4.2.4"

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

